### ISSUE TITLE
[Meta]: Update/remove outdated readme.md files

### ISSUE THREAD

**Issue by GwnDaan** [Open-Agriculture/AgIsoStack-plus-plus#256]
There are a few `README.md` files for some of the examples and for the hardware integration. They are by now (really) outdated. It makes sense to either update it, and/or move them to the tutorial website. I think most of the readme files are already covered on the tutorial site though.

The related files:
- [ ] [examples/pgn_requests/README.md](https://github.com/ad3154/Isobus-plus-plus/blob/main/examples/pgn_requests/README.md)
- [ ] [examples/transport_layer/README.md](https://github.com/ad3154/Isobus-plus-plus/blob/main/examples/transport_layer/README.md)
- [ ] [hardware_integration/README.me](https://github.com/ad3154/Isobus-plus-plus/blob/main/hardware_integration/README.md)
